/**
 * --------------------------------------------------------------------
 * docmd : the zero-config documentation engine.
 *
 * @package     @docmd/core (and ecosystem)
 * @website     https://docmd.io
 * @repository  https://github.com/docmd-io/docmd
 * @license     MIT
 * @copyright   Copyright (c) 2025-present docmd.io
 *
 * [docmd-source] - Please do not remove this header.
 * --------------------------------------------------------------------
 */

import path from 'path';
import fs from 'fs/promises';
import type { PluginDescriptor } from '@docmd/api';
import { outputPathToPathname, sanitizeUrl } from '@docmd/api';

export const plugin: PluginDescriptor = {
  name: 'llms',
  version: '0.8.0',
  capabilities: ['post-build']
};

export async function onPostBuild({ config, pages, outputDir, log }: any) {
  // Validation
  if (!config.url) {
    if (log) log('Skipping llms.txt: "url" is missing in config', 'SKIP');
    return;
  }

  const siteUrl = config.url.replace(/\/$/, '');
  const _options = config.plugins?.llms || {};

  if (log) log('Generating LLMs context files');

  // Build Content
  let content = `# ${config.title}\n\n`;
  content += `> Generated by docmd\n\n`;

  if (config.description) {
    content += `${config.description}\n\n`;
  }

  content += `## Documentation Files\n\n`;

  // Filter and Sort Pages
  const validPages = pages.filter(p => {
    // Skip noindex pages or pages explicitly excluded from llms
    if (p.frontmatter.noindex) return false;
    if (p.frontmatter.llms === false) return false;
    return true;
  });

  // Sort by URL for stability
  validPages.sort((a, b) => a.outputPath.localeCompare(b.outputPath));

  // Generate Links
  for (const page of validPages) {
    // Use centralised URL utility for consistent URL generation.
    // This is the single source of truth - no manual outputPath parsing.
    const pathname = outputPathToPathname(page.outputPath);
    const fullUrl = sanitizeUrl(siteUrl + pathname);
    const title = page.frontmatter.title || 'Untitled';

    content += `- [${title}](${fullUrl})\n`;

    if (page.frontmatter.description) {
      content += `  ${page.frontmatter.description}\n`;
    }
  }

  // Write llms.txt File
  await fs.writeFile(path.join(outputDir, 'llms.txt'), content);

  // Generate llms-full.txt containing the entire raw markdown concatenated
  let fullContent = `# ${config.title} - Full Context\n\n`;
  fullContent += `> Generated by docmd\n\n`;
  if (config.description) fullContent += `${config.description}\n\n`;
  fullContent += `---\n\n`;

  for (const page of validPages) {
    // Use centralised URL utility - same as above
    const pathname = outputPathToPathname(page.outputPath);
    const fullUrl = sanitizeUrl(siteUrl + pathname);
    const title = page.frontmatter.title || 'Untitled';

    fullContent += `## [${title}](${fullUrl})\n\n`;
    try {
      if (page.sourcePath) {
        const rawMd = await fs.readFile(page.sourcePath, 'utf8');
        fullContent += `${rawMd}\n\n---\n\n`;
      } else {
        fullContent += `*(Raw content unavailable)*\n\n---\n\n`;
      }
    } catch {
      if (log) log(`Skipping raw markdown: ${page.sourcePath}`, 'SKIP');
    }
  }

  await fs.writeFile(path.join(outputDir, 'llms-full.txt'), fullContent);
}