/**
 * --------------------------------------------------------------------
 * docmd : the zero-config documentation engine.
 *
 * @package     @docmd/core (and ecosystem)
 * @website     https://docmd.io
 * @repository  https://github.com/docmd-io/docmd
 * @license     MIT
 * @copyright   Copyright (c) 2025-present docmd.io
 *
 * [docmd-source] - Please do not remove this header.
 * --------------------------------------------------------------------
 */

import fs from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { TUI } from '@docmd/tui';
import { loadConfig } from '../utils/config-loader.js';
import { normalizeConfig } from '../utils/config-schema.js';

// Use synchronous read to avoid top-level await fragility
const pkgUrl = new URL('../../package.json', import.meta.url);
const { version } = JSON.parse(readFileSync(pkgUrl, 'utf-8'));

interface DeployOpts {
  docker?: boolean;
  nginx?: boolean;
  caddy?: boolean;
  force?: boolean;
  config?: string;
}

/**
 * Reads the user config (or zero-config defaults) and extracts
 * only the fields relevant to deployment scaffolding.
 *
 * Uses the same loadConfig → normalizeConfig pipeline as `docmd build`
 * and `docmd dev`, ensuring deploy output always matches the canonical
 * zero-config defaults even if they change in future versions.
 */
async function resolveDeployContext(configPath: string) {
  let config: any;
  try {
    config = await loadConfig(configPath, { isDev: false, quiet: true });
  } catch {
    // If config loading fails entirely (e.g. permission error, corrupt file),
    // run an empty config through normalizeConfig to get canonical defaults.
    // This ensures we never hardcode fallback values that could drift.
    config = normalizeConfig({});
  }

  // After loadConfig/normalizeConfig, all fields are guaranteed to exist
  // under their modern names. No fallback chains needed - normalizeConfig
  // is the single source of truth for all defaults.
  const title = config.title;
  const outDir = config.out;
  const siteUrl = config.url;
  const isSpa = config.layout?.spa !== false;
  const configFile = configPath !== 'docmd.config.js' ? configPath : null;

  // Extract hostname from URL for server_name / Caddy address
  let hostname = '';
  if (siteUrl) {
    try {
      hostname = new URL(siteUrl).hostname;
    } catch {
      hostname = siteUrl.replace(/^https?:\/\//, '').split('/')[0];
    }
  }

  return { title, outDir, siteUrl, hostname, isSpa, configFile, version };
}

/**
 * Writes a deployment file. Always overwrites to ensure configs
 * stay in sync with the current docmd.config.js.
 *
 * When --force is NOT set, shows a notice that a file was updated.
 * When --force IS set, silently regenerates.
 */
async function writeDeployFile(filePath: string, content: string, label: string): Promise<boolean> {
  await fs.writeFile(filePath, content, 'utf8');
  TUI.step(label, 'DONE');
  return true;
}

export async function generateDeployConfigs(opts: DeployOpts) {
  const cwd = process.cwd();
  let generatedCount = 0;

  // Resolve project context from user config or zero-config
  const ctx = await resolveDeployContext(opts.config || 'docmd.config.js');

  // Build the docmd build command line used inside Dockerfile
  const buildCmd = ctx.configFile ? `docmd build --config ${ctx.configFile}` : 'docmd build';

  // Log what config was detected
  TUI.section('Deployment Context');
  TUI.item('Project', ctx.title);
  TUI.item('Output', `${ctx.outDir}/`);
  if (ctx.hostname) {
    TUI.item('Host', ctx.hostname);
  }
  TUI.footer();

  if (opts.docker) {
    // Check if user also generated nginx.conf - if so, copy it into the container
    const hasNginxConf = opts.nginx || await fileExists(resolve(cwd, 'nginx.conf'));
    const nginxCopyLine = hasNginxConf
      ? 'COPY nginx.conf /etc/nginx/conf.d/default.conf'
      : '';

    const dockerfile = `# ---------------------------------------------------
# Dockerfile generated by docmd v${ctx.version}
# Project: ${ctx.title}
# https://docmd.io/deployment/docker
# ---------------------------------------------------

# Stage 1: Build the docmd site
FROM node:20-alpine AS builder
WORKDIR /app

# Copy dependency manifests first for optimal layer caching
COPY package*.json ./
RUN if [ -f package.json ]; then npm install --ignore-scripts; fi

# Copy the rest of the project
COPY . .

# Install the exact docmd core version used to configure this deployment
RUN npm install -g @docmd/core@${ctx.version}

# Build the site
RUN ${buildCmd}

# Stage 2: Serve with nginx
FROM nginx:alpine
${nginxCopyLine}
COPY --from=builder /app/${ctx.outDir} /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`;

    const dockerignore = `node_modules
${ctx.outDir}
dist
.git
.gitignore
.env
.env.*
*.md
!docs/**/*.md
.DS_Store
Thumbs.db
`;

    if (await writeDeployFile(resolve(cwd, 'Dockerfile'), dockerfile, 'Dockerfile')) generatedCount++;
    if (await writeDeployFile(resolve(cwd, '.dockerignore'), dockerignore, '.dockerignore')) generatedCount++;
  }

  if (opts.nginx) {
    const serverName = ctx.hostname || 'localhost';

    // SPA fallback block - only included when SPA mode is active
    const spaBlock = ctx.isSpa ? `
    # SPA Routing Fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
` : `
    location / {
        try_files $uri $uri/ =404;
    }
`;

    const nginxConf = `# ---------------------------------------------------
# nginx.conf generated by docmd v${ctx.version}
# Project: ${ctx.title}
# https://docmd.io/deployment/nginx
# ---------------------------------------------------

server {
    listen 80;
    server_name ${serverName};
    root /usr/share/nginx/html;
    index index.html;

    # Security
    server_tokens off;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;

    # GZIP Compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_min_length 256;
    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        text/xml
        application/xml
        application/xml+rss
        text/javascript
        image/svg+xml;
${spaBlock}
    # Custom 404
    error_page 404 /404.html;

    # Cache Control for Static Assets
    location ~* \\.(?:ico|css|js|gif|jpe?g|png|webp|avif|woff2?|eot|ttf|otf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, immutable";
    }
}
`;
    if (await writeDeployFile(resolve(cwd, 'nginx.conf'), nginxConf, 'nginx.conf')) generatedCount++;
  }

  if (opts.caddy) {
    const caddyAddress = ctx.hostname || ':80';

    // SPA fallback - only when SPA mode is active
    const spaCaddyLine = ctx.isSpa
      ? '    try_files {path} {path}/ /index.html'
      : '    try_files {path} {path}/';

    const caddyfile = `# ---------------------------------------------------
# Caddyfile generated by docmd v${ctx.version}
# Project: ${ctx.title}
# https://docmd.io/deployment/caddy
# ---------------------------------------------------

${caddyAddress} {
    root * ./${ctx.outDir}
    file_server

    # SPA Routing Fallback
${spaCaddyLine}

    # Security Headers
    header {
        X-Content-Type-Options "nosniff"
        X-Frame-Options "SAMEORIGIN"
        -Server
    }

    # Custom 404
    handle_errors {
        rewrite * /404.html
        file_server
    }

    # Cache Static Assets (6 months)
    @static {
        file
        path *.ico *.css *.js *.gif *.jpg *.jpeg *.png *.webp *.avif *.svg *.woff *.woff2 *.eot *.ttf *.otf
    }
    header @static Cache-Control "public, max-age=15552000, immutable"
}
`;
    if (await writeDeployFile(resolve(cwd, 'Caddyfile'), caddyfile, 'Caddyfile')) generatedCount++;
  }

  if (generatedCount === 0 && (opts.docker || opts.nginx || opts.caddy)) {
    TUI.warn('No deployment files were generated.');
  }
}

/** Simple file-exists check */
async function fileExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}