/**
 * --------------------------------------------------------------------
 * docmd : the zero-config documentation engine.
 *
 * @package     @docmd/core (and ecosystem)
 * @website     https://docmd.io
 * @repository  https://github.com/docmd-io/docmd
 * @license     MIT
 * @copyright   Copyright (c) 2025-present docmd.io
 *
 * [docmd-source] - Please do not remove this header.
 * --------------------------------------------------------------------
 */

import fs from 'fs';
import path from 'path';
import { execSync, execFileSync } from 'child_process';

import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const pluginsRegistry = require('../registry/plugins.json');

/**
 * Detects the package manager used in the current project by looking for lockfiles upwards.
 * Defaults to 'npm' if no lockfile is found.
 */
function getPackageManager(cwd) {
  let dir = cwd;
  while (dir !== path.parse(dir).root) {
    if (fs.existsSync(path.join(dir, 'pnpm-lock.yaml'))) return 'pnpm';
    if (fs.existsSync(path.join(dir, 'yarn.lock'))) return 'yarn';
    if (fs.existsSync(path.join(dir, 'bun.lockb'))) return 'bun';
    if (fs.existsSync(path.join(dir, 'package-lock.json'))) return 'npm';
    dir = path.dirname(dir);
  }
  return 'npm';
}

/**
 * Resolves plugin metadata from the registry, or builds a fallback object.
 */
function resolvePluginMeta(name) {
  if (pluginsRegistry[name]) {
    return pluginsRegistry[name];
  }
  
  throw new Error(`Plugin "${name}" not found in the official registry. For custom plugins, please install via your package manager and configure manually.`);
}

/**
 * Reads config and safely injects the plugin to the `plugins` object.
 */
function injectPluginToConfig(configPath, meta) {
  let content = '';
  if (fs.existsSync(configPath)) {
    content = fs.readFileSync(configPath, 'utf8');
  } else {
    // Scaffold minimal config if missing
    content = `module.exports = {\n  plugins: {}\n};\n`;
  }

  // Strip comments to avoid false positives (e.g., `// analytics: {}`)
  const strippedContent = content.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');

  const configKey = meta.configKey;

  // Check if plugin is already inside
  if (strippedContent.includes(`'${configKey}'`) || strippedContent.includes(`"${configKey}"`) || strippedContent.includes(`\`${configKey}\``) || strippedContent.includes(`${configKey}:`)) {
    return false; // Already installed
  }

  // Look for `plugins: {`
  const pluginsRegex = /plugins\s*:\s*\{/;
  const match = content.match(pluginsRegex);

  // Dynamically format multi-line configs to match indentation
  const formattedConfig = meta.defaultConfig.replace(/\n/g, '\n    ');
  const injectStr = `'${configKey}': ${formattedConfig}`;

  if (match) {
    content = content.replace(pluginsRegex, `plugins: {\n    ${injectStr},`);
  } else {
    // If there's no plugins object, we can try to inject it before the last closing brace
    const moduleExportsRegex = /module\.exports\s*=\s*(?:defineConfig\()?\{([\s\S]*?)\}(?:\))?;?/g;
    let matchE;
    let lastMatch;
    while ((matchE = moduleExportsRegex.exec(content)) !== null) {
      lastMatch = matchE;
    }
    if (lastMatch) {
      const closingBraceIndex = lastMatch.index + lastMatch[0].lastIndexOf('}');
      const prefix = content.substring(0, closingBraceIndex);
      const suffix = content.substring(closingBraceIndex);
      
      const insert = prefix.trim().endsWith(',') || prefix.trim().endsWith('{') ? 
        `\n  plugins: {\n    ${injectStr}\n  }\n` : 
        `,\n  plugins: {\n    ${injectStr}\n  }\n`;
        
      content = prefix + insert + suffix;
    } else {
      TUI.warn(`Could not automatically inject plugin into config file. Please add '${configKey}': ${meta.defaultConfig} manually to the plugins object.`);
      return false;
    }
  }

  fs.writeFileSync(configPath, content, 'utf8');
  return true;
}

/**
 * Removes the plugin from the config file.
 */
function removePluginFromConfig(configPath, meta) {
  if (!fs.existsSync(configPath)) return false;

  const content = fs.readFileSync(configPath, 'utf8');
  const configKey = meta.configKey;
  const escapedKey = configKey.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

  if (!content.includes(configKey)) {
    return false;
  }

  // This regex handles both multiline well-formatted configs, and poorly formatted tight inline configs 
  // generated by the scaffolding fallback e.g. `'search': {},}`
  const re1 = new RegExp(`\\s*['"\`]?${escapedKey}['"\`]?\\s*:\\s*\\{[^}]*\\}\\s*,?\\s*`, 'gm');
  
  // Replace active entries with empty string
  const newContent = content.replace(re1, '');

  if (content === newContent) {
    return false; // Regex didn't match (e.g. config differs from expected format)
  }

  fs.writeFileSync(configPath, newContent, 'utf8');
  return true;
}


import { TUI } from '@docmd/api';

async function installPlugin(pluginInput: string, opts: { verbose?: boolean } = {}) {
  const cwd = process.cwd();
  const pkgManager = getPackageManager(cwd);
  
  let meta;
  try {
    meta = resolvePluginMeta(pluginInput);
  } catch (err: any) {
    TUI.error('Installation Aborted', err.message);
    return;
  }
  const packageName = meta.package;

  TUI.section('Plugin Installation');
  TUI.step(`Installing ${packageName} via ${pkgManager}`, 'WAIT');

  let cmdExe = '';
  let cmdArgs: string[] = [];
  if (pkgManager === 'npm') { cmdExe = 'npm'; cmdArgs = ['install', packageName]; }
  else if (pkgManager === 'yarn') { cmdExe = 'yarn'; cmdArgs = ['add', packageName]; }
  else if (pkgManager === 'pnpm') { cmdExe = 'pnpm'; cmdArgs = ['add', packageName]; }
  else if (pkgManager === 'bun') { cmdExe = 'bun'; cmdArgs = ['add', packageName]; }

  if (pkgManager === 'npm' && !fs.existsSync(path.join(cwd, 'package.json'))) {
    cmdArgs.push('--no-save');
  }

  try {
    const stdioMode = opts.verbose ? 'inherit' : 'pipe';
    execFileSync(cmdExe, cmdArgs, { stdio: stdioMode, cwd });
    
    TUI.step(packageName, 'DONE');
    
    const configPath = path.join(cwd, 'docmd.config.js');
    TUI.divider('Configuration');
    TUI.step(`Activating ${meta.configKey}`, 'WAIT', TUI.blue);

    const injected = injectPluginToConfig(configPath, meta);
    if (injected) {
      TUI.step('Activation completed', 'DONE', TUI.blue);
    } else {
      TUI.step('Plugin already configured', 'SKIP', TUI.blue);
    }
    TUI.footer();
    TUI.success('Plugin successfully installed and activated.');

  } catch (err: any) {
    TUI.step(packageName, 'FAIL');
    TUI.footer();
    TUI.error(`Could not install ${packageName}`, opts.verbose ? err.message : 'Run with --verbose for detailed logs.');
  }
}

async function removePlugin(pluginInput: string, opts: { verbose?: boolean } = {}) {
  const cwd = process.cwd();
  const pkgManager = getPackageManager(cwd);
  
  let meta;
  try {
    meta = resolvePluginMeta(pluginInput);
  } catch (err: any) {
    TUI.error('Removal Aborted', err.message);
    return;
  }
  const packageName = meta.package;

  TUI.section('Plugin Removal');
  TUI.step(`Uninstalling ${packageName} via ${pkgManager}`, 'WAIT');

  let cmdExe = '';
  let cmdArgs: string[] = [];
  if (pkgManager === 'npm') { cmdExe = 'npm'; cmdArgs = ['uninstall', packageName]; }
  else if (pkgManager === 'yarn') { cmdExe = 'yarn'; cmdArgs = ['remove', packageName]; }
  else if (pkgManager === 'pnpm') { cmdExe = 'pnpm'; cmdArgs = ['remove', packageName]; }
  else if (pkgManager === 'bun') { cmdExe = 'bun'; cmdArgs = ['remove', packageName]; }

  try {
    const stdioMode = opts.verbose ? 'inherit' : 'pipe';
    execFileSync(cmdExe, cmdArgs, { stdio: stdioMode, cwd });
    
    TUI.step(packageName, 'DONE');
    
    const configPath = path.join(cwd, 'docmd.config.js');
    TUI.divider('Configuration');
    TUI.step(`Removing ${meta.configKey}`, 'WAIT', TUI.blue);

    const removed = removePluginFromConfig(configPath, meta);
    if (removed) {
      TUI.step('Cleanup completed', 'DONE', TUI.blue);
    } else {
      TUI.step('No config entry found', 'SKIP', TUI.blue);
    }
    TUI.footer();
    TUI.success('Plugin successfully uninstalled.');

  } catch (err: any) {
    TUI.step(packageName, 'FAIL');
    TUI.footer();
    TUI.error(`Could not remove ${packageName}`, err.message);
  }
}

export {
  installPlugin,
  removePlugin
};