/**
 * --------------------------------------------------------------------
 * docmd : the zero-config documentation engine.
 *
 * @package     @docmd/core (and ecosystem)
 * @website     https://docmd.io
 * @repository  https://github.com/docmd-io/docmd
 * @license     MIT
 * @copyright   Copyright (c) 2025-present docmd.io
 *
 * [docmd-source] - Please do not remove this header.
 * --------------------------------------------------------------------
 */

import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import chalk from 'chalk';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const pluginsRegistry = require('../registry/plugins.json');

/**
 * Detects the package manager used in the current project by looking for lockfiles upwards.
 * Defaults to 'npm' if no lockfile is found.
 */
function getPackageManager(cwd) {
  let dir = cwd;
  while (dir !== path.parse(dir).root) {
    if (fs.existsSync(path.join(dir, 'pnpm-lock.yaml'))) return 'pnpm';
    if (fs.existsSync(path.join(dir, 'yarn.lock'))) return 'yarn';
    if (fs.existsSync(path.join(dir, 'bun.lockb'))) return 'bun';
    if (fs.existsSync(path.join(dir, 'package-lock.json'))) return 'npm';
    dir = path.dirname(dir);
  }
  return 'npm';
}

/**
 * Resolves plugin metadata from the registry, or builds a fallback object.
 */
function resolvePluginMeta(name) {
  if (pluginsRegistry[name]) {
    return pluginsRegistry[name];
  }
  
  // Fallback for unofficial/custom plugins
  return {
    package: name,
    description: "Custom community plugin",
    configKey: name.replace('@docmd/plugin-', ''), // Best effort guess
    defaultConfig: "{}"
  };
}

/**
 * Reads config and safely injects the plugin to the `plugins` object.
 */
function injectPluginToConfig(configPath, meta) {
  let content = '';
  if (fs.existsSync(configPath)) {
    content = fs.readFileSync(configPath, 'utf8');
  } else {
    // Scaffold minimal config if missing
    content = `module.exports = {\n  plugins: {}\n};\n`;
  }

  // Strip comments to avoid false positives (e.g., `// analytics: {}`)
  const strippedContent = content.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');

  const configKey = meta.configKey;

  // Check if plugin is already inside
  if (strippedContent.includes(`'${configKey}'`) || strippedContent.includes(`"${configKey}"`) || strippedContent.includes(`\`${configKey}\``) || strippedContent.includes(`${configKey}:`)) {
    return false; // Already installed
  }

  // Look for `plugins: {`
  const pluginsRegex = /plugins\s*:\s*\{/;
  const match = content.match(pluginsRegex);

  // Dynamically format multi-line configs to match indentation
  const formattedConfig = meta.defaultConfig.replace(/\n/g, '\n    ');
  const injectStr = `'${configKey}': ${formattedConfig}`;

  if (match) {
    content = content.replace(pluginsRegex, `plugins: {\n    ${injectStr},`);
  } else {
    // If there's no plugins object, we can try to inject it before the last closing brace
    const moduleExportsRegex = /module\.exports\s*=\s*(?:defineConfig\()?\{([\s\S]*?)\}(?:\))?;?/g;
    let matchE;
    let lastMatch;
    while ((matchE = moduleExportsRegex.exec(content)) !== null) {
      lastMatch = matchE;
    }
    if (lastMatch) {
      const closingBraceIndex = lastMatch.index + lastMatch[0].lastIndexOf('}');
      const prefix = content.substring(0, closingBraceIndex);
      const suffix = content.substring(closingBraceIndex);
      
      const insert = prefix.trim().endsWith(',') || prefix.trim().endsWith('{') ? 
        `\n  plugins: {\n    ${injectStr}\n  }\n` : 
        `,\n  plugins: {\n    ${injectStr}\n  }\n`;
        
      content = prefix + insert + suffix;
    } else {
      console.warn(chalk.yellow(`Could not automatically inject plugin into config file. Please add '${configKey}': ${meta.defaultConfig} manually to the plugins object.`));
      return false;
    }
  }

  fs.writeFileSync(configPath, content, 'utf8');
  return true;
}

/**
 * Removes the plugin from the config file.
 */
function removePluginFromConfig(configPath, meta) {
  if (!fs.existsSync(configPath)) return false;

  const content = fs.readFileSync(configPath, 'utf8');
  const configKey = meta.configKey;

  if (!content.includes(configKey)) {
    return false;
  }

  // This regex handles both multiline well-formatted configs, and poorly formatted tight inline configs 
  // generated by the scaffolding fallback e.g. `'search': {},}`
  const re1 = new RegExp(`\\s*['"\`]?${configKey}['"\`]?\\s*:\\s*\\{[^}]*\\}\\s*,?\\s*`, 'gm');
  
  // Replace active entries with empty string
  const newContent = content.replace(re1, '');

  if (content === newContent) {
    return false; // Regex didn't match (e.g. config differs from expected format)
  }

  fs.writeFileSync(configPath, newContent, 'utf8');
  return true;
}


async function installPlugin(pluginInput: string, opts: { verbose?: boolean } = {}) {
  const cwd = process.cwd();
  const pkgManager = getPackageManager(cwd);
  const meta = resolvePluginMeta(pluginInput);
  const packageName = meta.package;

  if (opts.verbose) {
    console.log(chalk.cyan(`Installing ${packageName} using ${pkgManager}...`));
  } else {
    process.stdout.write(chalk.cyan(`Installing ${packageName}... `));
  }

  let installCmd = '';
  if (pkgManager === 'npm') installCmd = `npm install ${packageName}`;
  else if (pkgManager === 'yarn') installCmd = `yarn add ${packageName}`;
  else if (pkgManager === 'pnpm') installCmd = `pnpm add ${packageName}`;
  else if (pkgManager === 'bun') installCmd = `bun add ${packageName}`;

  // Use `--no-save` fallback for global / raw directories gracefully if it's npm
  if (pkgManager === 'npm' && !fs.existsSync(path.join(cwd, 'package.json'))) {
    installCmd += ' --no-save';
  }

  try {
    const stdioMode = opts.verbose ? 'inherit' : 'pipe';
    execSync(installCmd, { stdio: stdioMode, cwd });
    
    if (!opts.verbose) process.stdout.write(chalk.green(`Done\n`));
    else console.log(chalk.green(`Successfully installed ${packageName}.`));
    
    const configPath = path.join(cwd, 'docmd.config.js');
    console.log(chalk.cyan(`Injecting '${meta.configKey}' into docmd.config.js...`));

    const injected = injectPluginToConfig(configPath, meta);
    if (injected) {
      console.log(chalk.green(`Successfully activated '${meta.configKey}' in config.`));
    } else {
      console.log(chalk.yellow(`Plugin '${meta.configKey}' was already in config or could not be injected.`));
    }
  } catch (err) {
    if (!opts.verbose) process.stdout.write(chalk.red(`Failed\n`));
    console.error(chalk.red(`❌ Could not install plugin '${packageName}'.`));
    if (opts.verbose) {
      console.error(chalk.dim(err.message));
      if (err.stdout) console.error(err.stdout.toString());
      if (err.stderr) console.error(err.stderr.toString());
    } else {
      console.error(chalk.yellow(`Run with --verbose to see detailed logs.`));
    }
  }
}

async function removePlugin(pluginInput: string, opts: { verbose?: boolean } = {}) {
  const cwd = process.cwd();
  const pkgManager = getPackageManager(cwd);
  const meta = resolvePluginMeta(pluginInput);
  const packageName = meta.package;

  if (opts.verbose) {
    console.log(chalk.cyan(`Removing ${packageName} using ${pkgManager}...`));
  } else {
    process.stdout.write(chalk.cyan(`Removing ${packageName}... `));
  }

  let uninstallCmd = '';
  if (pkgManager === 'npm') uninstallCmd = `npm uninstall ${packageName}`;
  else if (pkgManager === 'yarn') uninstallCmd = `yarn remove ${packageName}`;
  else if (pkgManager === 'pnpm') uninstallCmd = `pnpm remove ${packageName}`;
  else if (pkgManager === 'bun') uninstallCmd = `bun remove ${packageName}`;

  try {
    const stdioMode = opts.verbose ? 'inherit' : 'pipe';
    execSync(uninstallCmd, { stdio: stdioMode, cwd });
    
    if (!opts.verbose) process.stdout.write(chalk.green(`Done\n`));
    else console.log(chalk.green(`Successfully uninstalled ${packageName}.`));
    
    const configPath = path.join(cwd, 'docmd.config.js');
    console.log(chalk.cyan(`Removing '${meta.configKey}' from docmd.config.js...`));

    const removed = removePluginFromConfig(configPath, meta);
    if (removed) {
      console.log(chalk.green(`Successfully deactivated '${meta.configKey}' in config.`));
    } else {
      console.log(chalk.yellow(`Plugin '${meta.configKey}' was not found in config or could not be removed automatically.`));
    }
  } catch (err) {
    if (!opts.verbose) process.stdout.write(chalk.red(`Failed\n`));
    console.error(chalk.red(`❌ Could not remove plugin '${packageName}'.`));
    if (opts.verbose) {
      console.error(chalk.dim(err.message));
    }
  }
}

export {
  installPlugin,
  removePlugin
};